[general]
import = [
"~/.config/alacritty/tokyo-night.toml",
]
[env]
TERM = "xterm-256color"

[window]

opacity = 0.88

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

startup_mode = "Maximized"


[font]

normal.family = "FiraMono Nerd Font"
#bold.family = "Cascadia Code PL"
#italic.family = "Cascadia Code PL"
#bold_italic.family = "Cascadia Code PL"

size = 18.0


[scrolling]
history = 5000




[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"
